name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-framework:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_15.3.app/Contents/Developer"
      - name: Test Framework
        run: make test-framework
  test-examples:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_15.3.app/Contents/Developer"
      - name: Test Examples
        run: make test-examples
